# Generated by Django 5.2.9 on 2025-12-19 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_amenity_name_en_amenity_name_ru_city_city_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='store.property'),
        ),
    ]
